name: RyViews
favicon: null
layout_spectrum: 0.43216511770151556
typography_spectrum: 0.9943454896565527
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.05086332792416215
  lightness: 0.23508707410655916
  saturation: 0.4505864353850484
  rhythmicContrast: 0.9640510871540755
purpose: []
